### ISSUE TITLE
Update `Board` to use UUID-based ids.

### ISSUE THREAD

**Issue by zorn** [elixirfocus/retro_taxi#13]
To help with alignment in that User rows are also using UUID-based id -- but more so we don't want board URLs to be guessable.

**Comment by ryguigas0** [comment]
Hey can you assign me this task and add the hacktoberfest tag?

**Comment by zorn** [comment]
Go for it! Thanks!!

**Comment by zorn** [comment]
PR in the works: #18

**Comment by zorn** [comment]
PR #18 merged. Thanks so much for the help!
